name: fl

on:
    workflow_dispatch:
    schedule:
        - cron: "5 2 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: fl

jobs:
    build:
        runs-on: ubuntu-latest        
        steps:
            #- uses: actions/checkout@v1
            - name: Checkout
              run: |
                  git clone -b master https://github.com/wudongdefeng/tem-update.git ~/jd
                               

            - name: 'Set up Python'
              uses: actions/setup-python@v1
              with:
                python-version: 3.7

            - name: 'Install requirements'
              run: pip install requests
            - name: run
              run: |
                  ls
                  
                                    
              env:   
                  JD_COOKIE: ${{ secrets.JD_COOKIE}}
                  JD_DEBUG: false
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN}}
                  TG_USER_ID: ${{ secrets.TG_USER_ID}}
                  QYWX_KEY: ${{ secrets.QYWX_KEY}}
                  QYWX_AM: ${{ secrets.QYWX_AM}}
             
