name: fruit

on:
    workflow_dispatch:
    schedule:
        - cron: "7 6-18 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: fruit

jobs:
    build:
        runs-on: ubuntu-latest        
        steps:
            #- uses: actions/checkout@v1
            - name: Checkout
              run: |
                  git clone -b master https://github.com/wudongdefeng/tem-update.git ~/jd
                  cp -r ~/jd/*.* /home/runner/work/jd-tencentscf/jd-tencentscf                  
                  sed -i '/GITHUB/,+6d' jddjCookie.js 
                  sed -i '/GITHUB/,+6d' jdCookie.js
                  
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.15.0
                  
            - name: run
              run: |
                  npm install                   
                  node jd_fruit.js                  
              env:   
                  JD_COOKIE: ${{ secrets.JD_COOKIE1}}
                  JD_DEBUG: false
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN}}
                  TG_USER_ID: ${{ secrets.TG_USER_ID}}
                  QYWX_KEY: ${{ secrets.QYWX_KEY}}
                  QYWX_AM: ${{ secrets.QYWX_AM}}
                  
