name: try

on:
    workflow_dispatch:
    schedule:
        - cron: "5 1 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: try

jobs:
    build:
        runs-on: ubuntu-latest        
        steps:
            #- uses: actions/checkout@v1
            - name: Checkout
              run: |
                  git clone -b jd_scripts https://github.com/Aaron-lv/sync.git ~/jd
                  git clone https://github.com/wudongdefeng/jd-temporary.git ~/tem
                  cp -r ~/jd/*.* /home/runner/work/jd-tencentscf/jd-tencentscf
                  cp ~/tem/jd_hyjcoin.py /home/runner/work/jd-tencentscf/jd-tencentscf                 
                   
                  sed -i '/GITHUB/,+6d' jdCookie.js
                  
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.15.0
                  
            - name: run
              run: |
                  
                  pip3 install -r requirments.txt
                  python jd_hyjcoin.py
                                    
              env:   
                  JD_COOKIE: ${{ secrets.JD_COOKIE}}
                  JD_DEBUG: false
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN}}
                  TG_USER_ID: ${{ secrets.TG_USER_ID}}
                  QYWX_KEY: ${{ secrets.QYWX_KEY}}
                  QYWX_AM: ${{ secrets.QYWX_AM}}
             
