name: jd推送 

on:
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: jd_pull
jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
      
    - name: time GMT+8 北京时间
      run: |
        sudo timedatectl set-timezone 'Asia/Shanghai' 
    - name: 获取当前日期
      id: date
      run: echo "::set-output name=DATE::$(date +'%Y-%m-%d %H:%M:%S')" 
   
    - uses: actions/checkout@v2
    - name: Clone source code 克隆源码
      run: |
        
        mkdir -p ~/.ssh
        echo -e "${{ secrets.USER_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com > ~/.ssh/known_hosts
        
        git clone -b master git@github.com:wudongdefeng/monk.git ./monk
        cp ./monk/*.* /home/runner/work/jd-tencentscf/jd-tencentscf
        
        bash wind.sh  

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3

   
        
    
    
