name: jddj_bean_plantBeans

on:
    workflow_dispatch:
    schedule:
        - cron: "1 2,13 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: plantBeans

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            #- uses: actions/checkout@v1
            - name: Checkout
              run: |
                  git clone -b main https://github.com/passerby-b/JDDJ ~/jd
                  cp -r ~/jd/*.* /home/runner/work/jddj/jddj                  
                  cp /home/runner/work/jddj/jddj/jdCookie1.js /home/runner/work/jddj/jddj/jdCookie.js
                  cp /home/runner/work/jddj/jddj/jddjCookie1.js /home/runner/work/jddj/jddj/jddjCookie1.js
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.15.0
                  
            - name: run
              run: |
                  
                  npm install                   
                  node jddj_bean.js
                  node jddj_plantBeans.js
              env:   
                  JD_COOKIE: ${{ secrets.JD_COOKIE}}
                  JD_DEBUG: ${{ secrets.JD_DEBUG}}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN}}
                  TG_USER_ID: ${{ secrets.TG_USER_ID}}
                  QYWX_KEY: ${{ secrets.QYWX_KEY}}
                  QYWX_AM: ${{ secrets.QYWX_AM}}
                  
