name: zjd

on:
    workflow_dispatch:
    schedule:
        - cron: "5 1 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: zjd

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16]

        steps:
            - uses: actions/checkout@v2
            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                node-version: "12.x"
            - run: npm install --production
            - run: sudo npm i -g ts-node
            - run: npm install typescript
                  
            # Runs typescript
            - name: Run tsc
              run: |
                git clone https://github.com/JDHelloWorld/jd_scripts.git jd_scripts
                cd ./jd_scripts
                npm install
                ts-node jd_zjd.ts
              env:   
                  JD_COOKIE: ${{ secrets.JD_COOKIE}}
